version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build Solution
          command: |
            cd ~/repo/src/Aiplugs.Elements
            version=$(echo $CIRCLE_TAG | sed 's/v//' -r)
            sed -i -e "s#<Version>1.0.0</Version>#<Version>$version</Version>#g" ./Aiplugs.Elements.csproj
            cd ~/repo/src
            dotnet build
      - save_cache:
          paths:
            - ~/repo
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
  push:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          command: |
            cd ~/repo/src/Aiplugs.Elements
            dotnet pack -c Release
            dotnet nuget push ./bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_TOKEN
workflows:
  version: 2
  default:
    jobs:
      - build
  publish:
    jobs:
      - build:
          filters:
            tags: 
              only: /.*/
            branches:
              ignore: /.*/
      - push:
          requires:
            - build
          filters:
            tags: 
              only: /^v[0-9]+(\.[0-9\-]+)*$/
            branches:
              ignore: /.*/